FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY . /src/
RUN dotnet publish -c Release -o /published Repro.Wasm/Repro.Wasm.csproj

FROM nginx:alpine as run
WORKDIR /usr/share/nginx/html
COPY --from=build /published/wwwroot .